<?php

$questions = [
    //Name de la empresa
    "como se llama la pasteleria?" => "Somos Cupcake Fantasy of Love un negocio en crecimiento, con el objetivo de seguir adelante, manteniendo la calidad de nuestros productos y de esa manera continuar entregando momentos de felicidad en esas fechas especiales, donde se busca mostrar el afecto por los que queremos y que mejor manera de hacerlo regalandole algo de 'Cupcake Fantasy of Love' (La fantasía del sabor).",
    "¿como se llama la pasteleria?" => "Somos Cupcake Fantasy of Love un negocio en crecimiento, con el objetivo de seguir adelante, manteniendo la calidad de nuestros productos y de esa manera continuar entregando momentos de felicidad en esas fechas especiales, donde se busca mostrar el afecto por los que queremos y que mejor manera de hacerlo regalandole algo de 'Cupcake Fantasy of Love' (La fantasía del sabor).",
    "cual es el nombre de la pasteleria?" => "Somos Cupcake Fantasy of Love un negocio en crecimiento, con el objetivo de seguir adelante, manteniendo la calidad de nuestros productos y de esa manera continuar entregando momentos de felicidad en esas fechas especiales, donde se busca mostrar el afecto por los que queremos y que mejor manera de hacerlo regalandole algo de 'Cupcake Fantasy of Love' (La fantasía del sabor).",
    "¿cual es el nombre de la pasteleria?" => "Somos Cupcake Fantasy of Love un negocio en crecimiento, con el objetivo de seguir adelante, manteniendo la calidad de nuestros productos y de esa manera continuar entregando momentos de felicidad en esas fechas especiales, donde se busca mostrar el afecto por los que queremos y que mejor manera de hacerlo regalandole algo de 'Cupcake Fantasy of Love' (La fantasía del sabor).",
    "como se llaman?" => "Somos Cupcake Fantasy of Love un negocio en crecimiento, con el objetivo de seguir adelante, manteniendo la calidad de nuestros productos y de esa manera continuar entregando momentos de felicidad en esas fechas especiales, donde se busca mostrar el afecto por los que queremos y que mejor manera de hacerlo regalandole algo de 'Cupcake Fantasy of Love' (La fantasía del sabor).",
    "¿como se llaman?" => "Somos Cupcake Fantasy of Love un negocio en crecimiento, con el objetivo de seguir adelante, manteniendo la calidad de nuestros productos y de esa manera continuar entregando momentos de felicidad en esas fechas especiales, donde se busca mostrar el afecto por los que queremos y que mejor manera de hacerlo regalandole algo de 'Cupcake Fantasy of Love' (La fantasía del sabor).",
    "quienes son?" => "Somos Cupcake Fantasy of Love un negocio en crecimiento, con el objetivo de seguir adelante, manteniendo la calidad de nuestros productos y de esa manera continuar entregando momentos de felicidad en esas fechas especiales, donde se busca mostrar el afecto por los que queremos y que mejor manera de hacerlo regalandole algo de 'Cupcake Fantasy of Love' (La fantasía del sabor).",
    "¿quienes son?" => "Somos Cupcake Fantasy of Love un negocio en crecimiento, con el objetivo de seguir adelante, manteniendo la calidad de nuestros productos y de esa manera continuar entregando momentos de felicidad en esas fechas especiales, donde se busca mostrar el afecto por los que queremos y que mejor manera de hacerlo regalandole algo de 'Cupcake Fantasy of Love' (La fantasía del sabor).",


    //Ubicación de la empresa
    "de donde es la pasteleria?" => "Somos del poblado de Jarretaderas, Nayarit.",
    "¿de donde es la pasteleria?" => "Somos del poblado de Jarretaderas, Nayarit.",
    "de donde son?" => "Somos del poblado de Jarretaderas, Nayarit.",
    "¿de donde son?" => "Somos del poblado de Jarretaderas, Nayarit.",
    "direccion" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "cual es su direccion?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿cual es su direccion?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "lugar de la pasteleria" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "donde se encuentra la pasteleria?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿donde se encuentra la pasteleria?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "cual es la direccion de la pasteleria?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿cual es la direccion de la pasteleria?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "donde esta la pasteleria?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿donde esta la pasteleria?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "ubicacion" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "como los ubico?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿como los ubico?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "donde se ubican?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿donde se ubican?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "en donde se ubican?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿en donde se ubican?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "donde estan ubicados?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿donde estan ubicados?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "donde los ubico?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿donde los ubico?" => "Estamos ubicados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "localizacion" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "como los localizo?" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿como los localizo?" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "donde se localizan?" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿donde se localizan?" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "donde estan localizados?" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿donde estan localizados?" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "donde los localizo?" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",
    "¿donde los localizo?" => "Estamos localizados en Av. Mexico 100, Costa Coral, 63735, Las Jarretaderas, Nayarit.",


    //Dudas
    "iniciar sesion" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "inicio de sesion" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "como inicio sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿como inicio sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "como iniciar sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿como iniciar sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "como se inicia sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿como se inicia sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "donde inicio sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿donde inicio sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "donde se inicia sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿donde se inicia sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "donde iniciar sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿donde iniciar sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "en donde inicio sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿en donde inicio sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "en donde se inicia sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿en donde se inicia sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "en donde iniciar sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿en donde iniciar sesion?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",

    "ingresar" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "ingreso" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "como ingreso?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿como ingreso?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "como ingresar?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿como ingresar?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "como se ingresa?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿como se ingresa?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "donde ingreso?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿donde ingreso?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "donde se ingresa?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿donde se ingresa?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "donde ingresar?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿donde ingresar?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "en donde ingreso?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿en donde ingreso?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "en donde se ingresa?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿en donde se ingresa?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "en donde ingresar?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",
    "¿en donde ingresar?" => "Tiene que dar click en el icono de Login posiscionado en la esquina superior derecha.",

    "estado del pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "ver estado del pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "ver el estado del pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como veo el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como veo el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como ver el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como ver el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como se ve el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como se ve el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde veo el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde veo el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde se ve el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde se ve el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde ver el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde ver el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde veo el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde veo el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde se ve el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde se ve el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde ver el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde ver el estado del pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",

    "pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "estado de mi pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "ver estado de mi pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "ver el estado de mi pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como veo el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como veo el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como ver el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como ver el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como se ve el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como se ve el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde veo el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde veo el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde se ve el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde se ve el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde ver el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde ver el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde veo el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde veo el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde se ve el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde se ve el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde ver el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde ver el estado de mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",

    "el pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "ver pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "ver el pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como veo el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como veo el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como ver el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como ver el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como se ve el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como se ve el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde veo el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde veo el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde se ve el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde se ve el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde ver el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde ver el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde veo el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde veo el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde se ve el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde se ve el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde ver el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde ver el pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",

    "mi pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "ver mi pedido" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como veo mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como veo mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como ver mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como ver mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "como se ve mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿como se ve mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde veo mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde veo mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde se ve mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde se ve mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "donde ver mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿donde ver mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde veo mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde veo mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde se ve mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde se ve mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "en donde ver mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",
    "¿en donde ver mi pedido?" => "Para visualizar el estado de su pedido, vaya a la página principal, de click en el icono de Login en la esquina superior derecha y seleccione PEDIDOS.",

    "cancelar pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "quiero cancelar pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "proceso para cancelar pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como cancelo pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como cancelo pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como cancelar pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como cancelar pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como se cancela pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como se cancela pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde cancelo pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde cancelo pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde se cancela pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde se cancela pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde cancelar pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde cancelar pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde cancelo pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde cancelo pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde se cancela pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde se cancela pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde cancelar pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde cancelar pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    
    "cancelar el pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "quiero cancelar el pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "proceso para cancelar el pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como cancelo el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como cancelo el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como cancelar el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como cancelar el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como se cancela el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como se cancela el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde cancelo el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde cancelo el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde se cancela el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde se cancela el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde cancelar el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde cancelar el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde cancelo el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde cancelo el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde se cancela el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde se cancela el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde cancelar el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde cancelar el pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",

    "cancelar mi pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "quiero cancelar mi pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "proceso para cancelar mi pedido" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como cancelo mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como cancelo mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como cancelar mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como cancelar mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "como se cancela mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿como se cancela mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde cancelo mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde cancelo mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde se cancela mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde se cancela mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "donde cancelar mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿donde cancelar mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde cancelo mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde cancelo mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde se cancela mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde se cancela mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "en donde cancelar mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",
    "¿en donde cancelar mi pedido?" => "Para cancelar su pedido contáctese con la administradora. <a id='mensaje_bot_error' href='https://wa.me/+523223227013'>Contacto</a>",



    //Name del chatbot
    "como te llamas?" => "Soy CakeBot y estoy para servirte",
    "¿como te llamas?" => "Soy CakeBot y estoy para servirte",
    "cual es tu nombre?" => "Soy CakeBot y estoy para servirte",
    "¿cual es tu nombre?" => "Soy CakeBot y estoy para servirte",
    "tienes nombre?" => "Soy CakeBot y estoy para servirte",
    "¿tienes nombre?" => "Soy CakeBot y estoy para servirte",
    "quien eres?" => "Soy CakeBot, una inteligencia artificial desarrollada por un grupo de estudiantes.",
    "¿quien eres?" => "Soy CakeBot, una inteligencia artificial desarrollada por un grupo de estudiantes.",


    //Función
    "cual es tu funcion?" => "Yo seré el encargado en brindarle apoyo y responder sus dudas con respecto a la empresa y sitio web.",
    "¿cual es tu funcion?" => "Yo seré el encargado en brindarle apoyo y responder sus dudas con respecto a la empresa y sitio web.",
    "que haces?" => "Yo seré el encargado en brindarle apoyo y responder sus dudas con respecto a la empresa y sitio web.",
    "¿que haces?" => "Yo seré el encargado en brindarle apoyo y responder sus dudas con respecto a la empresa y sitio web.",
    "para que sirves?" => "Yo seré el encargado en brindarle apoyo y responder sus dudas con respecto a la empresa y sitio web.",
    "¿para que sirves?" => "Yo seré el encargado en brindarle apoyo y responder sus dudas con respecto a la empresa y sitio web.",
    "funcion" => "Yo seré el encargado en brindarle apoyo y responder sus dudas con respecto a la empresa y sitio web.",


    //Info del chatbot
    "eres una inteligencia artificial?" => "Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "¿eres una inteligencia artificial?" => "Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "eres una ai?" => "Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "¿eres una ai?" => "Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "eres una ia?" => "Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "¿eres una ia?" => "Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "ai" => "¿Si tratas de preguntar de que si soy una Inteligencia artifical?; la respuesta es: Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "ai?" => "¿Si tratas de preguntar de que si soy una Inteligencia artifical?; la respuesta es: Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "ia" => "¿Si tratas de preguntar de que si soy una Inteligencia artifical?; la respuesta es: Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    "ia?" => "¿Si tratas de preguntar de que si soy una Inteligencia artifical?; la respuesta es: Si, al igual que Alexa, Asistente de Google, Siri, etc; solo que yo estoy limitado a ayudar y dar soporte con temas relacionados a la empresa 'Cupcake Fantasy of Love'.",
    
    "como puedo pagar?" => "El metodo de pago es en efectivo.",
    "¿como puedo pagar?" => "El metodo de pago es en efectivo.",
    "como se paga?" => "El metodo de pago es en efectivo.",
    "¿como se paga?" => "El metodo de pago es en efectivo.",
    "como pago?" => "El metodo de pago es en efectivo.",
    "¿como pago?" => "El metodo de pago es en efectivo.",
    "donde puedo pagar?" => "El metodo de pago es en efectivo.",
    "¿donde puedo pagar?" => "El metodo de pago es en efectivo.",
    "donde se paga?" => "El metodo de pago es en efectivo.",
    "¿donde se paga?" => "El metodo de pago es en efectivo.",
    "donde pago?" => "El metodo de pago es en efectivo.",
    "¿donde pago?" => "El metodo de pago es en efectivo.",
    "pago" => "El metodo de pago es en efectivo. Y se hace despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "pagar" => "El metodo de pago es en efectivo. Y se hace despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "cuando es el pago?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "¿cuando es el pago?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "cuando pago?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "¿cuando pago?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "cuando se paga?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "¿cuando se paga?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "cuando se realiza el pago?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "¿cuando se realiza el pago?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "cuando se hace el pago?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",
    "¿cuando se hace el pago?" => "Despues de que el status de su pedido cambien a listo para entregar, nos contactaremos con usted via telefonica y se acordará lugar y hora de entrega.",

    
    //Saludo
    "hola" => "Hola, ¿En que puedo ayudarte?",
    "un saludo" =>"¿Como te va?",
    "hello" =>"Un gusto de verte",
    "como estas?" => "Bien y gracias por preguntar.",
    "¿como estas?" => "Bien y gracias por preguntar.",


    //Respuesta a como te va
    "fantastico" => "que maravilla",
    "fantastic" => "que maravilla",
    "muy bien" => "Me alegra saberlo",
    "bien" => "Me alegra saberlo",
    "very good" => "Que bueno",
    "good" => "Que bueno",
    "de maravilla" => "Me alegro mucho",
 

    //Despedida
    "adios" => "Cuidate.",
    "hasta la proxima" => "Nos vemos pronto.",
    "nos vemos" => "Te estare esperando.",
    "bye" => "Good bye ♥.",
    "see you" => "See you lader ♥.",
    
    
    //Información del chatbot
    "what is your name?" =>" My name is CakeBot",
    "tu nombre es?" => "Mi nombre es " . $bot->getName(),
    "¿tu nombre es?" => "Mi nombre es " . $bot->getName(),
    "tu eres?" => "Yo soy un " . $bot->getGender(),
    "¿tu eres?" => "Yo soy un " . $bot->getGender()

];
?>